"""Stage 0c: extract structured data from raw-day files via Ollama structured output."""

import argparse
import json
import sys
from pathlib import Path

import requests
import yaml

try:
    from json_repair import repair_json as _repair_json
    def _json_repair(text: str) -> dict:
        return json.loads(_repair_json(text))
except ImportError:
    def _json_repair(text: str) -> dict:  # type: ignore[misc]
        raise RuntimeError("json-repair not installed; run: pip install json-repair")

# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

# JSON Schema passed to Ollama's format field for structured output.
# Excludes date/source_format/input_completion_score — those are carried
# through from frontmatter and never generated by the model.
_EXTRACT_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "emotional_climate": {"type": "string"},
        "energy_level": {
            "type": "string",
            "enum": ["high", "medium", "low", "mixed", "unclear"],
        },
        "spiritual_movement": {
            "type": "string",
            "enum": ["consolation", "desolation", "mixed", "unclear"],
        },
        "tasks": {"type": "array", "items": {"type": "string"}},
        "verses": {"type": "array", "items": {"type": "string"}},
        "creative_ideas": {"type": "array", "items": {"type": "string"}},
        "gratitude_and_consolations": {"type": "array", "items": {"type": "string"}},
        "people_mentioned": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "context": {
                        "type": "string",
                        "enum": ["friend", "family", "romantic", "work", "mentor", "other"],
                    },
                },
                "required": ["name", "context"],
            },
        },
        "questions_alive": {"type": "array", "items": {"type": "string"}},
        "struggles_or_fears": {"type": "array", "items": {"type": "string"}},
        "notable_phrases": {"type": "array", "items": {"type": "string"}},
        "summary": {"type": "string"},
    },
    "required": [
        "emotional_climate",
        "energy_level",
        "spiritual_movement",
        "tasks",
        "verses",
        "creative_ideas",
        "gratitude_and_consolations",
        "people_mentioned",
        "questions_alive",
        "struggles_or_fears",
        "notable_phrases",
        "summary",
    ],
}

_ENERGY_LEVELS = {"high", "medium", "low", "mixed", "unclear"}
_SPIRITUAL_MOVEMENTS = {"consolation", "desolation", "mixed", "unclear"}
_PEOPLE_CONTEXTS = {"friend", "family", "romantic", "work", "mentor", "other"}

# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def _parse_raw_day(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    parts = text.split("---\n", 2)
    if len(parts) < 3:
        raise ValueError(f"No YAML frontmatter found in {path}")
    fm = yaml.safe_load(parts[1])
    return {
        "date": str(fm["date"]),
        "source_format": fm["source_format"],
        "input_completion_score": float(fm["input_completion_score"]),
        "body": parts[2].strip(),
    }

# ---------------------------------------------------------------------------
# Video section stripping
# ---------------------------------------------------------------------------

def _is_section_start(line: str) -> bool:
    if line.startswith("##"):
        return True
    return bool(line) and ord(line[0]) > 0x2000


def _strip_video_section(body: str) -> str:
    """Remove the 📹 Daily Video Transcript section from new_template bodies.

    Strips from the line containing 📹 to the next emoji/## section start or EOF.
    No-op on legacy bodies (no 📹 present).
    """
    lines = body.splitlines()
    result: list[str] = []
    in_video = False
    for line in lines:
        if not in_video and "📹" in line:
            in_video = True
            continue
        if in_video and _is_section_start(line):
            in_video = False
        if not in_video:
            result.append(line)
    return "\n".join(result)

# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

_PROMPT_TEMPLATE = """\
Extract structured data from this personal daily reflection. Be faithful to what is \
written — capture intent, not just explicit statements. Leave fields empty when nothing \
is present.

DATE: {date}

REFLECTION TEXT:
{body}

Fill every field:
- emotional_climate: one honest sentence about the emotional tone of the whole day
- energy_level: high | medium | low | mixed | unclear
- spiritual_movement: consolation | desolation | mixed | unclear
- tasks: explicit tasks or clear intentions mentioned
- verses: scripture references or quoted prayer/liturgical texts
- creative_ideas: creative sparks, projects, or artistic intentions
- gratitude_and_consolations: specific moments of gratitude or consolation
- people_mentioned: each person with name and relational context \
(friend/family/romantic/work/mentor/other)
- questions_alive: open questions the person is sitting with
- struggles_or_fears: worries, fears, or struggles present (explicit or implied)
- notable_phrases: striking phrases worth preserving verbatim
- summary: 80-100 words capturing the whole day honestly, not just the hard parts

/no_think"""


def _build_prompt(date: str, body: str) -> str:
    return _PROMPT_TEMPLATE.format(date=date, body=body)


def _build_retry_prompt(date: str, body: str, error: str) -> str:
    return (
        f"The previous extraction failed validation with this error:\n  {error}\n"
        f"Re-extract, fixing exactly that error. The output must match the JSON schema.\n\n"
        + _build_prompt(date, body)
    )

# ---------------------------------------------------------------------------
# Ollama call
# ---------------------------------------------------------------------------

def _call_ollama(prompt: str, model: str, url: str) -> str:
    resp = requests.post(
        f"{url}/api/generate",
        json={
            "model": model,
            "prompt": prompt,
            "format": _EXTRACT_SCHEMA,
            "stream": False,
            "options": {
                "num_predict": 4000,
                "num_ctx": 8192,
            },
        },
        timeout=300,
    )
    resp.raise_for_status()
    return resp.json()["response"]

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _validate(data: dict) -> None:
    required = [
        "emotional_climate", "energy_level", "spiritual_movement",
        "tasks", "verses", "creative_ideas", "gratitude_and_consolations",
        "people_mentioned", "questions_alive", "struggles_or_fears",
        "notable_phrases", "summary",
    ]
    for field in required:
        if field not in data:
            raise ValueError(f"Missing required field: {field!r}")

    if data["energy_level"] not in _ENERGY_LEVELS:
        raise ValueError(
            f"Invalid energy_level {data['energy_level']!r}; "
            f"must be one of {sorted(_ENERGY_LEVELS)}"
        )
    if data["spiritual_movement"] not in _SPIRITUAL_MOVEMENTS:
        raise ValueError(
            f"Invalid spiritual_movement {data['spiritual_movement']!r}; "
            f"must be one of {sorted(_SPIRITUAL_MOVEMENTS)}"
        )

    list_fields = [
        "tasks", "verses", "creative_ideas", "gratitude_and_consolations",
        "questions_alive", "struggles_or_fears", "notable_phrases",
    ]
    for field in list_fields:
        if not isinstance(data[field], list):
            raise ValueError(f"Field {field!r} must be a list, got {type(data[field]).__name__}")

    for i, person in enumerate(data["people_mentioned"]):
        if not isinstance(person, dict):
            raise ValueError(f"people_mentioned[{i}] must be an object")
        if "name" not in person or "context" not in person:
            raise ValueError(f"people_mentioned[{i}] missing 'name' or 'context'")
        if person["context"] not in _PEOPLE_CONTEXTS:
            raise ValueError(
                f"people_mentioned[{i}] has invalid context {person['context']!r}; "
                f"must be one of {sorted(_PEOPLE_CONTEXTS)}"
            )

    if not isinstance(data["emotional_climate"], str):
        raise ValueError("'emotional_climate' must be a string")
    if not isinstance(data["summary"], str):
        raise ValueError("'summary' must be a string")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _assemble_extract(fm: dict, model_output: dict) -> dict:
    return {
        "date": fm["date"],
        "source_format": fm["source_format"],
        "input_completion_score": fm["input_completion_score"],
        **model_output,
    }


def _is_successful_extract(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return not data.get("extraction_failed", False)
    except (json.JSONDecodeError, OSError):
        return False


def _absence_extract(fm: dict) -> dict:
    return {
        "date": fm["date"],
        "source_format": "none",
        "input_completion_score": 0.0,
        "emotional_climate": "",
        "energy_level": "unclear",
        "spiritual_movement": "unclear",
        "tasks": [],
        "verses": [],
        "creative_ideas": [],
        "gratitude_and_consolations": [],
        "people_mentioned": [],
        "questions_alive": [],
        "struggles_or_fears": [],
        "notable_phrases": [],
        "summary": "",
    }


def _write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")

# ---------------------------------------------------------------------------
# Per-day pipeline
# ---------------------------------------------------------------------------

def _extract_one(raw_path: Path, out_dir: Path, model: str, url: str) -> None:
    fm = _parse_raw_day(raw_path)
    date = fm["date"]
    out_path = out_dir / f"{date}.json"

    if _is_successful_extract(out_path):
        print(f"  skip  {date}")
        return

    if fm["source_format"] == "none":
        _write_json(out_path, _absence_extract(fm))
        print(f"  ok    {date}  (absence — no model call)")
        return

    body = _strip_video_section(fm["body"])
    prompt = _build_prompt(date, body)
    error_msg = ""
    raw = ""

    # Attempt 1
    try:
        raw = _call_ollama(prompt, model, url)
        data = json.loads(raw)
        _validate(data)
        _write_json(out_path, _assemble_extract(fm, data))
        print(f"  ok    {date}")
        return
    except (json.JSONDecodeError, ValueError, requests.RequestException) as exc:
        error_msg = str(exc)
        print(f"  retry {date}: {error_msg}", file=sys.stderr)

    # Attempt 2 — retry with error in prompt
    try:
        raw = _call_ollama(_build_retry_prompt(date, body, error_msg), model, url)
        data = json.loads(raw)
        _validate(data)
        _write_json(out_path, _assemble_extract(fm, data))
        print(f"  ok    {date}  (retry)")
        return
    except (json.JSONDecodeError, ValueError, requests.RequestException) as exc:
        error_msg = str(exc)
        print(f"  repair {date}: {error_msg}", file=sys.stderr)

    # Attempt 3 — json-repair pass
    try:
        data = _json_repair(raw)
        _validate(data)
        _write_json(out_path, _assemble_extract(fm, data))
        print(f"  ok    {date}  (repaired)")
        return
    except Exception as exc:
        error_msg = str(exc)
        print(f"  FAIL  {date}: {error_msg}", file=sys.stderr)

    # Total failure — write stub so the day is visible, not silently dropped
    _write_json(out_path, {
        "date": date,
        "source_format": fm["source_format"],
        "input_completion_score": fm["input_completion_score"],
        "extraction_failed": True,
        "error": error_msg,
    })

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Stage 0c: extract structured data from raw-day files via Ollama."
    )
    parser.add_argument("--inputs", required=True, help="Directory of raw-day .md files")
    parser.add_argument("--out", required=True, help="Output directory for extract JSON files")
    parser.add_argument("--model", required=True, help="Ollama model name (e.g. qwen3:14b)")
    parser.add_argument(
        "--ollama-url",
        default="http://localhost:11434",
        help="Ollama base URL (default: http://localhost:11434)",
    )
    args = parser.parse_args()

    in_dir = Path(args.inputs)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    files = sorted(in_dir.glob("????-??-??.md"))
    if not files:
        print(f"No raw-day files found in {in_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Processing {len(files)} raw-day file(s) → {out_dir}")
    for f in files:
        _extract_one(f, out_dir, args.model, args.ollama_url)


if __name__ == "__main__":
    main()
